apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhopp-go-250225
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhopp-go-250225 
  name: rhopp-go-250225
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhopp-go-250225 
